import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createServer } from 'node:http';
import next from 'next';
import pg from 'pg';

const injected = globalThis.tixoVerificationPool;
const databaseUrl = process.env.TEST_DATABASE_URL;
test('production HTTP: admin authentication, candle references, aroma chapters, inventory and orders', { skip: !databaseUrl && !injected }, async t => {
  const schema = `tixo_http_${randomUUID().replaceAll('-', '')}`;
  const url = new URL(databaseUrl || 'postgresql://isolated-preview');
  url.searchParams.set('options', `-c search_path=${schema}`);
  const pool = injected || new pg.Pool({ connectionString:url.toString() });
  await pool.query(`CREATE SCHEMA ${schema}`);
  if (injected) await pool.query(`SET search_path TO ${schema}`);
  process.env.DATABASE_URL=url.toString();
  const uploadDir=await mkdtemp(path.join(tmpdir(),'tixo-http-uploads-'));
  process.env.UPLOAD_DIR=uploadDir;
  process.env.ADMIN_PASSWORD=randomUUID(); process.env.SESSION_SECRET=randomUUID();
  globalThis.tihoPool=pool; globalThis.tihoSchemaReady=undefined;
  const app=next({dev:false,dir:process.cwd()});
  await app.prepare();
  const server=createServer(app.getRequestHandler());
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  t.after(async()=>{ await new Promise(resolve=>server.close(resolve)); await app.close(); await pool.query(`DROP SCHEMA ${schema} CASCADE`); await pool.end(); await rm(uploadDir,{recursive:true,force:true}); });
  const base=`http://127.0.0.1:${server.address().port}`;
  const call=(path, options={})=>fetch(base+path,options);
  const json=body=>({headers:{'content-type':'application/json'},body:JSON.stringify(body)});
  assert.equal((await call('/api/products?admin=1')).status,401);
  assert.equal((await call('/api/scents?admin=1')).status,401);
  assert.equal((await call('/api/colors?admin=1')).status,401);
  assert.equal((await call('/api/colors',{method:'POST',...json({name:'Без входа',hex:'#123456',active:true})})).status,401);
  assert.equal((await call('/api/forms?admin=1')).status,401);
  assert.equal((await call('/api/forms',{method:'POST',...json({name:'Без входа',shape:'shell',active:true})})).status,401);
  assert.equal((await call('/api/products/1/stock',{method:'PATCH',...json({stock:5,expectedStock:3})})).status,401);
  assert.equal((await call('/api/scents/1/profile',{method:'PATCH',...json({})})).status,401);
  assert.equal((await call('/api/orders')).status,401);
  assert.equal((await call('/api/admin/login',{method:'POST',...json({password:'wrong'})})).status,401);
  const malformed=await call('/api/admin/session',{headers:{cookie:'tiho_admin=NaN.'+'a'.repeat(64)}});
  assert.deepEqual(await malformed.json(),{authenticated:false});
  const login=await call('/api/admin/login',{method:'POST',...json({password:process.env.ADMIN_PASSWORD})});
  assert.equal(login.status,200);
  assert.match(login.headers.get('set-cookie'),/HttpOnly/i);
  assert.match(login.headers.get('set-cookie'),/SameSite=strict/i);
  const cookie=login.headers.get('set-cookie').split(';')[0];
  const admin=(path,options={})=>call(path,{...options,headers:{...options.headers,cookie}});
  assert.deepEqual(await (await admin('/api/admin/session')).json(),{authenticated:true});
  const scents=await (await admin('/api/scents?admin=1')).json();
  assert.equal(scents.length,30);assert.equal(scents.filter(scent=>scent.image?.startsWith("/assets/aromas/")).length,26);
  const colors=await (await call('/api/colors')).json();
  assert.equal(colors.length,4);
  assert.equal('color' in scents[0],false);
  const newColor=await admin('/api/colors',{method:'POST',...json({name:'Лавандовый',hex:'#AABBCC',active:true})});
  assert.equal(newColor.status,201);
  const lavender=await newColor.json();
  assert.equal(lavender.hex,'#aabbcc');
  assert.equal((await admin(`/api/colors/${lavender.id}`,{method:'PATCH',...json({...lavender,name:'Лаванда'})})).status,200);
  assert.equal((await admin(`/api/colors/${lavender.id}`,{method:'DELETE'})).status,200);
  const createdScent=await admin('/api/scents',{method:'POST',...json({name:'Новый аромат без цвета',description:'',notes:[],active:true})});
  assert.equal(createdScent.status,201);
  const edited={...scents[0],profile:undefined,name:'Проверенная композиция',notes:['вишня','миндаль'],color:'#bc1931'};
  assert.equal((await admin(`/api/scents/${edited.id}`,{method:'PATCH',...json(edited)})).status,200);
  assert.equal((await (await call('/api/scents')).json())[0].name,edited.name);
  const silhouette=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR42mNgAAIAAAUAAen63NgAAAAASUVORK5CYII=','base64');
  const shapeData=new FormData();shapeData.set('name','Форма HTTP');shapeData.set('active','true');shapeData.set('silhouette',new File([silhouette],'silhouette.png',{type:'image/png'}));
  const createdForm=await admin('/api/forms',{method:'POST',body:shapeData});
  assert.equal(createdForm.status,201);
  const shape=await createdForm.json();
  assert.equal(shape.shape,null);assert.match(shape.silhouette,/^\/api\/uploads\/.+\.png$/);
  const stored=await call(shape.silhouette);assert.equal(stored.status,200);assert.equal(stored.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await stored.arrayBuffer()),silhouette);
  assert.equal((await admin(`/api/forms/${shape.id}`,{method:'PATCH',...json({...shape,name:'Ракушка HTTP'})})).status,200);
  const profile={top:{notes:'Лимон',description:'Яркое начало'},heart:{notes:'Инжир',description:'Мягкое сердце'},base:{notes:'Сандал',description:'Долгий шлейф'}};
  assert.equal((await admin(`/api/scents/${edited.id}/profile`,{method:'PATCH',...json(profile)})).status,200);
  assert.deepEqual((await (await call('/api/scents')).json()).find(s=>s.id===edited.id).profile,profile);
  assert.equal((await admin(`/api/scents/${edited.id}`,{method:'PATCH',...json(edited)})).status,200);
  assert.deepEqual((await (await call('/api/scents')).json()).find(s=>s.id===edited.id).profile,profile);
  const form=new FormData();
  for(const [key,value] of Object.entries({formId:shape.id,colorId:colors[0].id,scentId:scents[0].id,notes:'Размер 12 см',price:1800,stock:3,published:true})) form.set(key,String(value));
  const saved=await admin('/api/products',{method:'POST',body:form});
  assert.equal(saved.status,201);
  const product=await saved.json();
  assert.equal(product.form.silhouette,shape.silhouette);assert.equal(product.form.shape,null); assert.equal(product.name,'Ракушка HTTP');assert.equal(product.colorId,colors[0].id);assert.equal(product.scentId,scents[0].id);assert.equal(product.stock,3);
  const customer={customerName:'Проверка',phone:'+79990000000',email:'test@example.com',address:'Тестовый адрес',delivery:'Самовывоз'};
  const line={productId:product.id,scentId:scents[0].id,colorId:colors[0].id,quantity:1};
  const wrong=await call('/api/orders',{method:'POST',...json({...customer,requestKey:randomUUID(),items:[{...line,colorId:colors[1].id}]})});
  assert.equal(wrong.status,409);
  const placed=await call('/api/orders',{method:'POST',...json({...customer,requestKey:randomUUID(),items:[line]})});
  assert.equal(placed.status,201);
  const orders=await (await admin('/api/orders')).json();
  const order=orders.find(item=>item.items.some(line=>line.productId===product.id));
  assert.equal(order.items.length,1); assert.equal(order.total,1800);assert.equal(order.items[0].colorName,colors[0].name);assert.equal(order.items[0].silhouette,shape.silhouette);
  assert.equal((await admin(`/api/products/${product.id}/stock`,{method:'PATCH',...json({stock:9,expectedStock:3})})).status,409);
  const stock=await admin(`/api/products/${product.id}/stock`,{method:'PATCH',...json({stock:5,expectedStock:2})});
  assert.equal(stock.status,200);assert.equal((await stock.json()).stock,5);
  assert.equal((await admin(`/api/orders/${order.id}`,{method:'DELETE'})).status,200);
  assert.equal((await (await admin('/api/products?admin=1')).json()).find(p=>p.id===product.id).stock,6);
  form.set('stock','6');form.set('expectedStock','6');form.set('notes','Обновлено вручную');
  assert.equal((await admin(`/api/products/${product.id}`,{method:'PATCH',body:form})).status,200);
  for(const [kind,id] of [['forms',shape.id],['colors',colors[0].id],['scents',scents[0].id]])assert.equal((await admin(`/api/${kind}/${id}`,{method:'DELETE'})).status,409);
  shapeData.set('name','Изменённый силуэт');
  const replaced=await admin(`/api/forms/${shape.id}`,{method:'PATCH',body:shapeData});assert.equal(replaced.status,200);const replacement=await replaced.json();assert.notEqual(replacement.silhouette,shape.silhouette);
  assert.equal((await call(shape.silhouette)).status,200);
  assert.equal((await (await admin('/api/products?admin=1')).json()).find(p=>p.id===product.id).form.silhouette,replacement.silhouette);
  shapeData.set('silhouette',new File(['<svg/>'],'bad.svg',{type:'image/svg+xml'}));assert.equal((await admin('/api/forms',{method:'POST',body:shapeData})).status,400);
  const spare=await (await admin('/api/forms',{method:'POST',...json({name:'Пустая форма',shape:'arch',active:true})})).json();
  assert.equal((await admin(`/api/forms/${spare.id}`,{method:'DELETE'})).status,200);
  const publicForms=await (await call('/api/forms')).json();
  assert.equal(publicForms.find(form=>form.id===shape.id).silhouette,replacement.silhouette);
  const aromaProfile={top:{notes:'Цедра',description:'Первая глава'},heart:{notes:'Чай',description:'Вторая глава'},base:{notes:'Кедр',description:'Третья глава'}};
  const namedResponse=await admin('/api/scents',{method:'POST',...json({name:'Чай из мастерской',description:'Готовая композиция',notes:['чай'],active:true,profile:aromaProfile})});assert.equal(namedResponse.status,201);const named=await namedResponse.json();assert.deepEqual(named.profile,aromaProfile);
  const aromaRecipe={formId:shape.id,color:'ivory',scentId:named.id};const aromaRequest={...customer,requestKey:randomUUID(),items:[{customRecipe:aromaRecipe,quantity:1}]};
  const aromaOrderResponse=await call('/api/orders',{method:'POST',...json(aromaRequest)});assert.equal(aromaOrderResponse.status,201);const aromaReceipt=await aromaOrderResponse.json();
  const snapshot=(await (await admin('/api/orders')).json()).find(order=>order.orderNumber===aromaReceipt.orderNumber);assert.equal(snapshot.items[0].scentName,named.name);assert.deepEqual(snapshot.items[0].aromaProfile,aromaProfile);
  assert.equal((await admin(`/api/scents/${named.id}`,{method:'PATCH',...json({...named,active:false,profile:{...aromaProfile,top:{notes:'Новая нота',description:'Новое начало'}}})})).status,200);
  assert.equal((await call('/api/orders',{method:'POST',...json({...aromaRequest,requestKey:randomUUID()})})).status,409);assert.equal((await call('/api/orders',{method:'POST',...json(aromaRequest)})).status,201);
  form.set('photos','[{"upload":0},{"upload":1}]');form.append('images',new File([silhouette],'one.png',{type:'image/png'}));form.append('images',new File([silhouette],'two.png',{type:'image/png'}));form.set('expectedImages','[]');
  const multiResponse=await admin(`/api/products/${product.id}`,{method:'PATCH',body:form});assert.equal(multiResponse.status,200);const multi=await multiResponse.json();assert.equal(multi.images.length,2);assert.equal(multi.image,multi.images[0]);
  for(const photo of multi.images)assert.equal((await call(photo)).status,200);
  form.delete('images');form.set('expectedImages',JSON.stringify(multi.images));form.set('photos',JSON.stringify([{url:multi.images[1]}]));
  const coverResponse=await admin(`/api/products/${product.id}`,{method:'PATCH',body:form});assert.equal(coverResponse.status,200);assert.equal((await coverResponse.json()).image,multi.images[1]);assert.equal((await call(multi.images[0])).status,200);
  assert.deepEqual((await (await call('/api/products')).json()).find(p=>p.id===product.id).images,[multi.images[1]]);
  const customRecipe={formId:shape.id,color:'red',top:'lemon',heart:'fig',base:'oud'};
  const customRequest={...customer,requestKey:randomUUID(),items:[{customRecipe,quantity:1}]};
  const customResponse=await call('/api/orders',{method:'POST',...json(customRequest)});assert.equal(customResponse.status,201);const receipt=await customResponse.json();assert.equal(receipt.total,0);assert.equal(receipt.quotePending,true);
  const savedCustom=(await (await admin('/api/orders')).json()).find(order=>order.orderNumber===receipt.orderNumber);
  assert.equal(savedCustom.items[0].formName,'Изменённый силуэт');assert.equal(savedCustom.items[0].silhouette,replacement.silhouette);assert.deepEqual(savedCustom.items[0].customRecipe,customRecipe);
  assert.equal((await (await admin('/api/products?admin=1')).json()).find(p=>p.id===product.id).stock,6);
  assert.equal((await admin(`/api/forms/${shape.id}`,{method:'PATCH',...json({name:'Форма отключена',active:false})})).status,200);
  assert.equal((await (await call('/api/forms')).json()).some(form=>form.id===shape.id),false);
  assert.equal((await call('/api/orders',{method:'POST',...json({...customRequest,requestKey:randomUUID()})})).status,409);
  const retry=await call('/api/orders',{method:'POST',...json(customRequest)});assert.equal(retry.status,201);assert.equal((await retry.json()).orderNumber,receipt.orderNumber);
  assert.equal((await call(`/api/products/${product.id}`,{method:'DELETE'})).status,401);
  assert.equal((await admin(`/api/products/${product.id}`,{method:'DELETE'})).status,200);
  assert.equal((await (await admin('/api/products?admin=1')).json()).some(p=>p.id===product.id),false);
  assert.equal((await call(multi.images[1])).status,200);
  for(const portrait of scents.filter(scent=>scent.image?.startsWith('/assets/aromas/'))){const asset=await call(portrait.image);assert.equal(asset.status,200);assert.match(asset.headers.get('content-type'),/image\/webp/);}
  const portraitData=new FormData();portraitData.set('data',JSON.stringify({name:'HTTP портрет',description:'Сохранённое описание',notes:[],active:true,profile:aromaProfile}));portraitData.set('image',new File([silhouette],'portrait.png',{type:'image/png'}));
  assert.equal((await call('/api/scents',{method:'POST',body:portraitData})).status,401);
  const portraitResponse=await admin('/api/scents',{method:'POST',body:portraitData});assert.equal(portraitResponse.status,201);const portrait=await portraitResponse.json();assert.equal((await call(portrait.image)).status,200);assert.deepEqual(portrait.profile,aromaProfile);
  const libraryImage=await admin(`/api/scents/${portrait.id}`,{method:'PATCH',...json({...portrait,image:'/assets/aromas/pure-jasmine.webp'})});assert.equal(libraryImage.status,200);assert.equal((await libraryImage.json()).image,'/assets/aromas/pure-jasmine.webp');
  assert.equal((await admin(`/api/scents/${portrait.id}`,{method:'PATCH',...json({...portrait,image:null})})).status,200);assert.equal((await (await call('/api/scents')).json()).find(s=>s.id===portrait.id).image,null);
  const content=new FormData(); content.set('key','hero.title'); content.set('kind','text'); content.set('value','Работает сохранение');
  assert.equal((await admin('/api/content',{method:'PATCH',body:content})).status,200);
  assert.equal((await (await admin('/api/content')).json())['hero.title'].value,'Работает сохранение');
  assert.equal((await admin('/api/admin/logout',{method:'POST'})).status,200);
});
